#!/usr/bin/env bash

set -e

ove echo yellow "mark multiple entries with TAB, jump between selections with ctrl-j and ctrl-k"
echo "$ seq 1 1000 | fzf --multi --bind=ctrl-j:next-selected,ctrl-k:prev-selected"
sleep 2
seq 1 1000 | fzf --multi --bind=ctrl-j:next-selected,ctrl-k:prev-selected || true
